# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-02 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('include_only_released', models.BooleanField(default=True)),
                ('include_only_departments', models.TextField()),
                ('exclude_departments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NameMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('coolshop_name', models.CharField(max_length=255)),
                ('feed_field_name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['feed', 'order'],
            },
        ),
        migrations.CreateModel(
            name='BaseCSVFeed',
            fields=[
                ('basefeed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feeds.BaseFeed')),
            ],
            bases=('feeds.basefeed',),
        ),
        migrations.AddField(
            model_name='namemapping',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_mapping', to='feeds.BaseFeed'),
        ),
        migrations.AlterUniqueTogether(
            name='namemapping',
            unique_together=set([('order', 'coolshop_name', 'feed_field_name', 'feed'), ('order', 'feed')]),
        ),
    ]
